- hosts: localhost
  connection: local

  vars:
    image_base: atlassian
    #registry: "docker.example.com"
    maintainer: "Dieter Verhelst <info@werus.be>"

  roles:
    - role: generate-all
      tags: generate
    - role: build-all
      tags: build

# Alternatively, you can only keep a selected list of versions present here. And only build those required.
# example:
#  roles:
#    - { role: atlassian-jira, version: 7.2.1, java: 8 }
#    - { role: atlassian-jira, version: 7.2.3, java: 8 }
#    - { role: atlassian-confluence, version: 6.0.1, java: 8 }
#    - { role: atlassian-confluence, version: 5.10.0, java: 8 }
#    - { role: atlassian-bitbucket, version: 4.14.4, java: 8 }
#    - role: build-all
#
#
# This would build all required dependency-containers and your required versions
